USE brewmaster_db;

INSERT INTO beer (beer_name, beer_desc) VALUES ("Boulevard Wheat", "a lively, refreshing ale with a natural citrusy flavor and distinctive cloudy appearance.");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Bud Light", "an American-style pale lager produced by Anheuser-Busch");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Coors Light", "a 4.2% ABV light beer brewed in Golden, Colorado");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Shock Top", "a traditional Belgian-style wheat ale that has a naturally cloudy and light golden color with a smooth, refreshing taste");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Root Beer", "a sweet North American soft drink traditionally made using the sassafras tree");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Guinness", "a Irish dry stout that originated in the brewery of Arthur Guinness");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Corona", "a pale lager produced by Cervecería Modelo in Mexico");
INSERT INTO beer (beer_name, beer_desc) VALUES ("PABST Blue Ribbon", "an American lager beer sold by Pabst Brewing Company, established in Milwaukee, Wisconsin");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Rolling Rock", "a American Adjunct Lager style beer brewed by Latrobe Brewing Co.");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Boulevard Pale Ale", "a smooth, fruity, well-balanced beer with year-round appeal");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Mike's Hard Lemonade", "an alcoholic lemon-flavored malt beverage, with an alcohol content of 5 percent.");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Sam Adams Boston Lager", "a Vienna Lager style beer brewed by Boston Beer Company");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Red Stripe Lager", "a American Adjunct Lager style beer brewed by Desnoes & Geddes Limited in Kingston, Jamaica.");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Modelo Especial", "a pilsener type beer, was introduced to the market in 1966. Today it is sold in glass bottles as well as cans");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Ad Adstra Ale" "A full bodied Ale that uses a hint of hops to balance the sweetness that comes from three different malt varieties");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Stella Artois", "a Belgian pilsner of between 4.8 and 5.2% ABV which was first brewed by Brouwerij Artois in Leuven, Belgium");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Budweiser", "an American-style pale lager produced by Anheuser-Busch");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Sapporo Original", " a Japanese Rice Lager style beer brewed by Sapporo Breweries Ltd. in Tokyo");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Yuengling Original Lager", "rich amber color, medium-bodied flavor and distinct character. It's brewed with roasted caramel malt for a subtle sweetness and a combination of cluster and cascade hops.");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Kirin Ichiban", "a American Lager style beer brewed by Kirin Brewery Company");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Boulevard Hazy IPA", "Exchanging upfront bitterness for massive hop additions at the end of the boil and in dry-hopping, we’ve created a juicy, hazy IPA bursting with tropical fruit flavors and aromas of nectary citrus.");
INSERT INTO beer (beer_name, beer_desc) VALUES ("Boulevard NutCracker", "hearty, warming brew is a classic winter ale, deep amber in color, with hints of molasses balanced by the spiciness of Chinook hops.");

INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Boulevard Wheat", "ToughNut",5,"It's really good, especially with a lemon");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Coors Light", "brubbagrump",4,"it's a nice beer after a long day of work");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Shock Top", "1toomany2",2,"i'm not a big fan of the orange zest");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Guinness", "buttermeup8",4,"it's a nice beer to have while you watch the game");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Budweiser", "whigs",3,"standard fare, not bad not great");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Bud Light", "ekiT",2,"cheap and light, but still alright");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Red Stripe Lager", "drewandYou",3,"the bottle makes it too expensive, still good though");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Ad Adstra Ale", "snakeydrake",4,"every time i have this beer it tastes great");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Yuengling Original Lager", "xacesxdeepbluex",4,"nice summer beer");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Yuengling Original Lager", "spunnups",3,"nice winter beer");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Sam Adams Boston Lager", "freefornow",4,"founded a flavor country in my mouth");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Boulevard Wheat", "egglayingbird",4,"great beer, nice refreshing flavor");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Boulevard NutCracker", "beerdrinker1",5,"warms you tum tum on a cold day");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("Budweiser", "beerdestroyer",2,"cheap and cheap");
INSERT INTO reviews (review_beer, review_username, score, review) VALUES ("PABST Blue Ribbon", "ultradrink",1,"ugh dont even get me started!");
